services:
  traefik:
    image: traefik:v3.5
    command:
      - "--api.insecure=true"        # Aktivera Traefiks dashboard (ej för produktion)
      - "--providers.docker=true"    # Läs labels från Docker
      - "--entrypoints.web.address=:80" # Entrypoint på port 80
    ports:
      - "80:80"
      - "8080:8080"                  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flaskapp:
    build: ./flaskapp   # mappen där Dockerfile ligger
    container_name: flaskapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaskapp.rule=Host(`flaskapp.localhost`)"
      - "traefik.http.services.flaskapp.loadbalancer.server.port=8000"